version: '3.7'

services:
  idempiere:
    image: jpiere:8.21
    volumes:
      - idempiere_config:/opt/idempiere/configuration
      - idempiere_plugins:/opt/idempiere/plugins
      - idempiere_log:/opt/idempiere/log
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
volumes:
  idempiere_plugins:
  idempiere_config:
  idempiere_log:
  postgres_data:
  postgres_log:
